# Generated by Django 3.1.7 on 2021-04-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('fwt', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('edu_no', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('cap_gain', models.CharField(blank=True, max_length=50, null=True)),
                ('cap_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_pw', models.CharField(blank=True, max_length=50, null=True)),
                ('native_country', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
